### ISSUE TITLE
change body color 

### ISSUE THREAD

**Issue by AntonA1990** [milan1990-anridc/02-Starting-Project#2]
I've changed body color
```css
body {
  background-color: #798080;
  color: #0fdfdf;
  text-align: center;
}
```
